--------------------------------------------------------
--  File created - Sunday-September-20-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GASTO
--------------------------------------------------------

  CREATE TABLE "CASHFLOW"."FORECAST"
   (	"ID_GASTO" NUMBER(19,0), 
	"GASTO_TYPE_CODE" VARCHAR2(31 BYTE),
	"ANIO" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"FECHA_COMPRA" DATE, 
	"IMPORTE" NUMBER(19,4), 
	"MES" NUMBER(10,0), 
	"MONEDA" VARCHAR2(10 BYTE), 
	"ID_CENTRO_COSTO_FK" NUMBER(19,0), 
	"ID_TIPO_GASTO_FK" NUMBER(19,0), 
	"CANTIDAD_CUOTAS" NUMBER(10,0), 
	"CUOTA_NUMERO" NUMBER(10,0), 
	"IMPORTE_TOTAL" NUMBER(19,4), 
	"ID_TARJETA_CREDITO_FK" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013265
--------------------------------------------------------

  CREATE UNIQUE INDEX "CASHFLOW"."SYS_C0013265" ON "CASHFLOW"."GASTO" ("ID_GASTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GASTO
--------------------------------------------------------

  ALTER TABLE "CASHFLOW"."GASTO" ADD PRIMARY KEY ("ID_GASTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CASHFLOW"."GASTO" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "CASHFLOW"."GASTO" MODIFY ("IMPORTE" NOT NULL ENABLE);
  ALTER TABLE "CASHFLOW"."GASTO" MODIFY ("FECHA_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "CASHFLOW"."GASTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CASHFLOW"."GASTO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "CASHFLOW"."GASTO" MODIFY ("ID_GASTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GASTO
--------------------------------------------------------

  ALTER TABLE "CASHFLOW"."GASTO" ADD CONSTRAINT "FK_GASTO_ID_CENTRO_COSTO_FK" FOREIGN KEY ("ID_CENTRO_COSTO_FK")
	  REFERENCES "CASHFLOW"."CENTRO_COSTO" ("ID_CENTRO_COSTO") ENABLE;
  ALTER TABLE "CASHFLOW"."GASTO" ADD CONSTRAINT "FK_GASTO_ID_TARJETA_CREDITO_FK" FOREIGN KEY ("ID_TARJETA_CREDITO_FK")
	  REFERENCES "CASHFLOW"."TARJETA_CREDITO" ("ID_TARJETA_CREDITO") ENABLE;
  ALTER TABLE "CASHFLOW"."GASTO" ADD CONSTRAINT "FK_GASTO_ID_TIPO_GASTO_FK" FOREIGN KEY ("ID_TIPO_GASTO_FK")
	  REFERENCES "CASHFLOW"."TIPO_GASTO" ("ID_TIPO_GASTO") ENABLE;
