CREATE TABLE CENTRO_COSTO (ID_CENTRO_COSTO NUMBER(19) NOT NULL, DESCRIPCION VARCHAR2(250) NOT NULL, NOMBRE VARCHAR2(250) NOT NULL, PRIMARY KEY (ID_CENTRO_COSTO))
CREATE TABLE GASTO (ID_GASTO NUMBER(19) NOT NULL, GASTO_TYPE_CODE VARCHAR2(31) NULL, ANIO NUMBER(10) NOT NULL, DESCRIPCION VARCHAR2(255) NOT NULL, FECHA_COMPRA DATE NOT NULL, IMPORTE NUMBER(19,4) NOT NULL, MES NUMBER(10) NOT NULL, MONEDA VARCHAR2(10) NULL, ID_CENTRO_COSTO_FK NUMBER(19) NULL, ID_TIPO_GASTO_FK NUMBER(19) NULL, CANTIDAD_CUOTAS NUMBER(10) NULL, CUOTA_NUMERO NUMBER(10) NULL, IMPORTE_TOTAL NUMBER(19,4) NULL, ID_TARJETA_CREDITO_FK NUMBER(19) NULL, PRIMARY KEY (ID_GASTO))
CREATE TABLE TARJETA_CREDITO (ID_TARJETA_CREDITO NUMBER(19) NOT NULL, BANCO_EMISOR VARCHAR2(250) NOT NULL, DESCRIPCION VARCHAR2(250) NOT NULL, NOMBRE VARCHAR2(250) NOT NULL, PRIMARY KEY (ID_TARJETA_CREDITO))
CREATE TABLE TIPO_GASTO (ID_TIPO_GASTO NUMBER(19) NOT NULL, DESCRIPCION VARCHAR2(250) NOT NULL, GRUPO_GASTO VARCHAR2(250) NOT NULL, NOMBRE VARCHAR2(250) NOT NULL, PRIMARY KEY (ID_TIPO_GASTO))
CREATE TABLE FORECAST (ID_FORECAST NUMBER(19) NOT NULL, ANIO NUMBER(10) NOT NULL, DESCRIPCION VARCHAR2(255) NOT NULL, FECHA_COMPRA DATE NOT NULL, IMPORTE NUMBER(19,4) NOT NULL, MES NUMBER(10) NOT NULL, MONEDA VARCHAR2(10) NULL, ID_TIPO_GASTO_FK NUMBER(19) NULL, PRIMARY KEY (ID_FORECAST))
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_ID_CENTRO_COSTO_FK FOREIGN KEY (ID_CENTRO_COSTO_FK) REFERENCES CENTRO_COSTO (ID_CENTRO_COSTO)
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_ID_TIPO_GASTO_FK FOREIGN KEY (ID_TIPO_GASTO_FK) REFERENCES TIPO_GASTO (ID_TIPO_GASTO)
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_ID_TARJETA_CREDITO_FK FOREIGN KEY (ID_TARJETA_CREDITO_FK) REFERENCES TARJETA_CREDITO (ID_TARJETA_CREDITO)
ALTER TABLE FORECAST ADD CONSTRAINT FK_FORECAST_ID_TIPO_GASTO_FK FOREIGN KEY (ID_TIPO_GASTO_FK) REFERENCES TIPO_GASTO (ID_TIPO_GASTO)
CREATE SEQUENCE TIPO_GASTO_SEQ START WITH 1
CREATE SEQUENCE GASTO_SEQ START WITH 1
CREATE SEQUENCE CENTRO_COSTO_SEQ START WITH 1
CREATE SEQUENCE FORECAST_SEQ START WITH 1
CREATE SEQUENCE TARJETA_CREDITO_SEQ START WITH 1
