ALTER TABLE GASTO DROP CONSTRAINT FK_GASTO_ID_CENTRO_COSTO_FK
ALTER TABLE GASTO DROP CONSTRAINT FK_GASTO_ID_TIPO_GASTO_FK
ALTER TABLE GASTO DROP CONSTRAINT FK_GASTO_ID_TARJETA_CREDITO_FK
ALTER TABLE FORECAST DROP CONSTRAINT FK_FORECAST_ID_TIPO_GASTO_FK
DROP TABLE CENTRO_COSTO
DROP TABLE GASTO
DROP TABLE TARJETA_CREDITO
DROP TABLE TIPO_GASTO
DROP TABLE FORECAST
DROP SEQUENCE TIPO_GASTO_SEQ
DROP SEQUENCE GASTO_SEQ
DROP SEQUENCE CENTRO_COSTO_SEQ
DROP SEQUENCE FORECAST_SEQ
DROP SEQUENCE TARJETA_CREDITO_SEQ
